services:
  rabbitmq-despacho:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-despacho
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - despacho-net

  despacho-app:
    image: dcruzv/cdy2204-despacho:latest
    container_name: despacho-app
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq-despacho
    volumes:
      - /mnt/efs:/app/efs
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-despacho
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin123
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    networks:
      - despacho-net

networks:
  despacho-net:
    driver: bridge