version: "3.8"

services:
  rabbitmq-despacho:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-despacho
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - despacho-net

  despacho-app:
    image: dcruzv/cdy2204-despacho:latest
    container_name: despacho-app
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq-despacho
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-despacho
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin123
    networks:
      - despacho-net

networks:
  despacho-net:
    driver: bridge