spring.application.name=despacho

spring.datasource.url=jdbc:oracle:thin:@inscripciondb_tp?TNS_ADMIN=./wallet
spring.datasource.username=ADMIN
spring.datasource.password=OracleOracle19c
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cloudcdy2204.b2clogin.com/cloudcdy2204.onmicrosoft.com/b2c_1_signupsignin_despacho/discovery/v2.0/keys